version: '3'

services:
  rpcserver:
    image: rpc/server:v0.0.1
    volumes:
      - .:/opt/rpcserver
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 127.0.0.1:5000:5000
      - 0.0.0.0:5000:5000
