#!/bin/bash

echo ----Creating sku110k venv and installing packages----
cd sku110k
python3 -m venv env
/opt/rpcserver/sku110k/env/bin/pip install numpy==1.16.3
/opt/rpcserver/sku110k/env/bin/pip install -r requirements.txt
echo ----Creating retail-product-classifier venv and installing packages----
cd ../
cd retail-product-classifier-server
python3.8 -m venv env
/opt/rpcserver/retail-product-classifier-server/env/bin/pip install --upgrade pip
/opt/rpcserver/retail-product-classifier-server/env/bin/pip install -r requirements.txt
echo ----Creating encoder venv and installing packages----
cd ../
cd encoder
python3 -m venv env
/opt/rpcserver/encoder/env/bin/pip install --upgrade pip
/opt/rpcserver/encoder/env/bin/pip install -r requirements.txt